version: 2
jobs:
  build:
    working_directory: ~/netcore-workbook
    docker:
      - image: microsoft/dotnet:2.1-sdk
    branches:
      only:
        - master
    steps:
      - run:
          name: print current directory
          command: pwd
      - run:
          name: Change to lesson directory
          command: cd Lesson08/StartOfLesson
      - run:
          name: Restore packages for all projects in solution
          command: netcore restore
      - run:
          name: Build all projects in solution
          command: netcore build
      - run:
          name: Run tests in test project
          command: dotnet test .\BaseProject.Test\BaseProject.Test.csproj
